services:
  frontend:
    ports:
      - "3000:3000"
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    restart: unless-stopped
